#language: android 
#jdk: oraclejdk8

#components: 
#  - tools
#  - tools
#  - platform-tools
#  - extra-google-google-play-services
#  - extra

language: node_js
node_js: 
-11.6.0
cache: yarn

install: 
  - yarn install

script: 
  - yarn test
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh_pages