language: node_js
node_js: 
-11.6.0
cache: yarn

install: 
  - yarn install

script: 
  - yarn test
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main